/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordgame;

import java.util.Random;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("Player one, please enter your name:");
        Scanner pOneName = new Scanner(System.in);
        System.out.println("Player two, please enter your name:");
        Scanner pTwoName = new Scanner(System.in);

        WordGame gameOne = new WordGame(new WordChooser(), new Masker(), pOneName.nextLine());
        WordGame gameTwo = new WordGame(new WordChooser(), new Masker(), pTwoName.nextLine());
        WordGame[] players = {gameOne, gameTwo};
        Integer current = new Random().nextInt(2);

        System.out.println("Welcome! Today the word to guess is:");
        System.out.println("Player one:" + gameOne.getWordToGuess());
        System.out.println("Player two:" + gameTwo.getWordToGuess());

        do {
            System.out.println(players[current].getName() + ": enter one letter to guess (" + players[current].getRemainingAttempts() +" attempts remaining):");
            System.out.println(players[current].getWordToGuess());
            Scanner userInput = new Scanner(System.in);
            Character letter = userInput.nextLine().charAt(0);
            if (players[current].guessLetter(letter)) {
                System.out.println("Right!");
            } else {
                System.out.println("Wrong...");
            }
            System.out.println("\n");

            if (players[current].isGameWon()) {
                System.out.println(players[current].name + " you have won!");
                break;
            }

            if (players[current].isGameLost()) {
                System.out.println("You have lost!");
                break;
            }

            if (current == 0) {
                current = 1;
            } else {
                current = 0;
            }

        } while (players[current].getRemainingAttempts() > 0);
    }
}
